version: '3.7'
services:
  web:
    build: web
    restart: always
    # Security: delete ports on prod
    ports:
      - 5000:5000
    environment:
      - DEBUG=0
    networks:
      - flask_network
    env_file:
      - .env
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network
  db:
    image: postgres:13
    restart: always
    # Security: delete ports on prod
    ports:
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=os.environ.get('PG_USER')
      - POSTGRES_PASSWORD=os.environ.get('PG_PASS')
      - POSTGRES_DB=os.environ.get('PG_DB')
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  flask_network:

volumes:
  postgres_data:
